name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug", "triage"]
projects: ["octo-org/1", "octo-org/44"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 1.0.2 (Default)
        - 1.0.3 (Edge)
      default: 0
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com). 
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
   - type: markdown
    attributes:
      value: |
    
    









        # Pull Request Template

        ## Description
        <!--- Describe your changes in detail -->

        ## Type of Change
        <!--- Place a 'x' in all the boxes that apply: -->
        - [ ] Bug fix (non-breaking change which fixes an issue)
        - [ ] New feature (non-breaking change which adds functionality)
        - [ ] Breaking change (fix or feature that would cause existing functionality to change)
        - [ ] Documentation update

        ## Related Issue
        <!--- This project only accepts pull requests related to open issues -->
        <!--- If suggesting a new feature or change, please discuss it in an issue first -->
        <!--- If fixing a bug, there should be an issue describing it with steps to reproduce -->
        <!--- Please link to the issue here: -->

        ## Motivation and Context
        <!--- Why is this change required? What problem does it solve? -->

        ## How Has This Been Tested?
        <!--- Please describe in detail how you tested your changes. -->
        <!--- Include details of your testing environment, and the tests you ran to -->
        <!--- see how your change affects other areas of the code, etc. -->

        ## Screenshots (if appropriate):

        ## Checklist:
        <!--- Go over all the following points, and place an 'x' in all the boxes that apply. -->
        <!--- If you're unsure about any of these, don't hesitate to ask. We're here to help! -->
        - [ ] My code follows the code style of this project.
        - [ ] My change requires a change to the documentation.
        - [ ] I have updated the documentation accordingly.
        - [ ] I have read the **CONTRIBUTING** document.
        - [ ] I have added tests to cover my changes.
        - [ ] All new and existing tests passed.

        ## Dropdown Example
        <!--- This section will not render as a functional dropdown in GitHub, but will be visible in the raw Markdown. -->
        ```html
        <select>
          <option value="bug">Bug fix</option>
          <option value="feature">New feature</option>
          <option value="docs">Documentation update</option>
        </select>
