name: CI Issue
description: Report a bug related to the automation
title: "[BUG] "
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this issue. Please provide the details below.
        Make sure to [link the important code section](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-a-permanent-link-to-a-code-snippet) via githubs permalinks.

  - type: textarea
    id: problem
    attributes:
      label: Problem description
      description: Describe the issue
      placeholder: Describe the issue
