name: Bug Report - Single File
description: Report your bug here if its a small one(one file), otherwise please create a PR [here](https://github.dev/Mupu/testo).
title: "[Bug]: "
body:
  - type: checkboxes
    id: general
    attributes:
      label: General
      options:
        - label: I've looked for similar bugs
          required: true
         - label: This bug fits into a single file
          required: true
        - label: I've already reported the bug to Jon
        - label: I will create a PR for this bug
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: Bug Type
      description: What type of bug is this?
      options:
        - Runtime (leaks, weird behaviour etc)
        - Compiletime (smth doesn't compile altough it should, etc)
        - Compiler Crash (outside compile-time execution crash)
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: Categorization
      description: What category does this bug belong to the most / What feature triggered the bug?
      options:
        - #if
        - #insert
        - leak
        - std:process
        - std:autorun
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      placeholder: Please fill this out if it is a more complicated bug.

  - type: textarea
    id: workaround
    attributes:
      label: Workaround
      placeholder: If you have a workaround, please share it here.

  - type: textarea
    id: bug_snippet
    attributes:
      label: Short Code Snipped
      placeholder: Please put your code to reproduce the bug here.
      render: c
    validations:
      required: true