name: Bug Report - Single File (Automated PR)
description: Report your bug here if its a small one(one file).
title: "[SB]: fasdfasdfasdf multiple"
body:
  - type: checkboxes
    id: general
    attributes:
      label: General
      options:
        - label: "I've looked for similar bugs"
          required: true
        - label: "This bug fits into a single file"
          required: true
        - label: "I've already reported the bug to Jon"
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: Expected Error Code
      description: What error code is expected to pass the test?
      options:
        - 0 (Default)
        - 1 (Error)
        - 3 (Internal Compiler Crash)
      default: 0
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Categorization
      description: What category does this bug belong to the most / What features triggered the bug?
      multiple: true
      options:
        - if
        - insert
        - leak
        - std:process
        - std:autorun
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      placeholder: Please fill this out if it is a more complicated bug.
      description: Please fill this out if it is a more complicated bug.

  - type: textarea
    id: workaround
    attributes:
      label: Workaround
      placeholder: If you have a workaround, please share it here.
      description: If you have a workaround, please share it here.

  - type: textarea
    id: bug_snippet
    attributes:
      label: Short Code Snippet
      placeholder: Please put your code to reproduce the bug here.
      description: Please put your code to reproduce the bug here.
      render: c
    validations:
      required: true