name: Suggestion
description: Thanks for trying to improve this project.
title: "[SUGGESTION] "

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to improve this project. Please provide the details below.
        Make sure to [link the important code section](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-a-permanent-link-to-a-code-snippet) via githubs permalinks.

  - type: textarea
    id: suggestion
    attributes:
      label: Discription
      description: Describe your suggestion
      placeholder: Describe your suggestion
