name: Create automatic PR from SB issue

on:
  workflow_dispatch: # Manual trigger
  # issues:
  #   types: [opened, edited] # @todo remove edited

jobs:
  create_pr_from_sb_issue:
    runs-on: [self-hosted, windows]

    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with: 
          token: ${{ steps.app-token.outputs.token }}
          persist-credentials: false

      # Use the app-token to trigger pull_request event
      - name: Create a new PR from SB Issue
        id: create_pr_from_sb_issue
        uses: actions/github-script@v7
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          script: |
            const createPRFromSBIssue = require('./.github/workflows/1_SB_issue_to_PR.js');
            const prNumber = await createPRFromSBIssue({ github, context, exec });
            core.setOutput('prNumber', prNumber);


