name: 1_SB_issue_to_PR_synchronizer

on:
  workflow_dispatch: # Manual trigger
  issues:
    types: [opened, edited] # new issues will be converted to PR
  pull_request:
    types: [edited] # edited PRs will update the PR

jobs:
  convertSBIssueToPRAndSynchronize:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with: 
          token: ${{ steps.app-token.outputs.token }}
          persist-credentials: false

      # Use the app-token to trigger validation
      - name: Create a new PR from SB Issue
        uses: actions/github-script@v7
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          script: |
            const convertSBIssueToPRAndSynchronize = require('./.github/workflows/1_SB_issue_to_PR_synchronizer.js');
            await convertSBIssueToPRAndSynchronize({ github, context, exec });


