name: Convert SB Issue to PR

on:
  workflow_dispatch: # Manual trigger
  issues:
    types: [opened]
  pull_request:
    types: [edited]

jobs:
  convertSBIssueToPR:
    runs-on: [ubuntu-latest]
    # runs-on: [self-hosted]

    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with: 
          token: ${{ steps.app-token.outputs.token }}
          persist-credentials: false

      # Use the app-token to trigger pull_request event
      - name: Create a new PR from SB Issue
        id: convertSBIssueToPR
        uses: actions/github-script@v7
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          script: |
            const convertSBIssueToPR = require('./.github/workflows/1_SB_issue_to_PR.js');
            await convertSBIssueToPR({ github, context, exec });


