name: 3_run_test_suit_and_update

on:
  workflow_dispatch: # Manual trigger
  push: # @todo uncomment
    branches:
      - master

permissions:
  issues: write

concurrency:
  group: ${{ github.workflow }}

jobs:
  run-test-suit:
    strategy:
      matrix:
        # This decides all relevant platforms. Platforms that are not in here
        # will not be tested and completely ignored. This is a good way to
        # to disable them.
        platform: [linux, windows] # :platformSpecific

    runs-on: 
     - self-hosted
     - ${{ matrix.platform }}

    steps:
      # @todo check if we really need git for all workflows
      - name: Verify Git is Installed
        uses: actions/github-script@v7
        with:
          script: |
            const { execSync } = require('child_process');

            try {
              // Try to execute the 'git --version' command
              execSync('git --version', { stdio: 'ignore' });
              console.log('Git is installed.');
            } catch (error) {
              // Fail the action if git is not installed
              core.setFailed('Git is not installed on the runner.');
            }

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Bug Suit
        uses: actions/github-script@v7
        with:
          script: |
            const { runTestSuitAndGatherOutput } = require('./.github/workflows/3_run_test_suit_and_update.js');
            await runTestSuitAndGatherOutput({ github, context, exec, io });

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: test_results_${{ matrix.platform }}
          path: test_results.json
          retention-days: 1 # we only need this for the next job



  update_github_files_and_issues:
    needs: run-test-suit
    runs-on: [self-hosted]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # :platformSpecific
      - name: Download Windows test results
        uses: actions/download-artifact@v4
        continue-on-error: true
        with:
          name: test_results_windows
          path: windows

      - name: Download Linux test results
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          name: test_results_linux
          path: linux

      - name: Update Github Files and Issues
        uses: actions/github-script@v7
        with:
          script: |
            const { updateGithubIssuesAndFiles } = require('./.github/workflows/3_run_test_suit_and_update.js');
            await updateGithubIssuesAndFiles({ github, context, exec, io });