name: Add current Compiler Version Label to Issue/PR

on:
  workflow_dispatch: # Manual trigger
  # pull_request:
  #   types: [opened]
  # issues:
  #   types: [opened, edited]
  

jobs:
  add_compiler_label:
    runs-on: [self-hosted, windows]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Add Compiler Label
      uses: actions/github-script@v7
      with:
        script: |
          // create current version label if not exists
          const { createCurrentCompilerVersionLabel } = require('./.github/workflows/create_label.js');
          const jaiVersion = await createCurrentCompilerVersionLabel({github, context, exec});

          // add label to issue
          await github.rest.issues.addLabels({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            labels: [ jaiVersion ]
          });
