name: Run Test Suit

on:
  # push:
  #   branches:
  #     - master
  workflow_dispatch: # Manual trigger

jobs:
  run_test_suit:
    runs-on: [self-hosted, windows]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Bug Suit
        uses: actions/github-script@v7
        with:
          script: |
            const bugSuit = require('./.github/workflows/bug_suit.js');
            await bugSuit({github, context, exec});
