name: Comment On PR Close

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
  

jobs:
  add_compiler_label:
    runs-on: [self-hosted, windows]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Add Compiler Label
      uses: actions/github-script@v7
      with:
        script: |
          console.log( "${{ github.event_name }}" );
          
          // get current jai version
          const { createCurrentVersionLabel } = require('./.github/workflows/create_label.js');
          const jai_version = await createCurrentVersionLabel({github, context});
