name: Create Compiler Label

on:
  workflow_dispatch: # Manual trigger
  workflow_call:

jobs:
  create_compiler_label:
    runs-on: [self-hosted, windows]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Create Compiler Label if it does not exist
      uses: actions/github-script@v7
      with:
        script: |
          // get current jai version
          const get_jai_version = require('./.github/workflows/jai_version.js');
          const jai_version = await get_jai_version();

          // Specify the Berlin time zone and desired format
          let options = {
            timeZone: 'Europe/Berlin',
            year: 'numeric',
            month: '2-digit',
            day: '2-digit',
            hour: '2-digit',
            minute: '2-digit',
            second: '2-digit'
          };
          // Format the date and time
          let berlinTime = new Intl.DateTimeFormat('en-CA', options).format(new Date());
          // Extract the date part (YYYY-MM-DD)
          let berlinDate = berlinTime.split(',')[0];
          console.log(berlinTime);
          
          // Check if the label exists
          const { data: labels } = await github.rest.issues.listLabelsForRepo({
            owner: context.repo.owner,
            repo: context.repo.repo,
          });

          const labelExists = labels.some(label => label.name === jai_version);

          // If the label doesn't exist, create it
          if (!labelExists) {
            await github.rest.issues.createLabel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: jai_version,
            });
          }
