name: Create Compiler Label

on:
  workflow_dispatch: # Manual trigger
  workflow_call:

jobs:
  create_compiler_label:
    runs-on: [self-hosted, windows]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Create Compiler Label if it does not exist
      uses: actions/github-script@v7
      with:
        script: |
          // get current jai version
          const get_jai_version = require('./.github/workflows/jai_version.js');
          const jai_version = await get_jai_version();

           // create label
          const createLabel = require('./.github/workflows/create_label.js');
          await createLabel({context, github, jai_version});

          
