name: Create automatic PR from issue

on:
  issues:
    types: [opened, edited]

jobs:
  create_pr:
    runs-on: [self-hosted, windows]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create a new issue
        uses: actions/github-script@v7
        with:
          script: |
            const createPr = require('./.github/workflows/create_pr.js');
            await createPr({github, context});


