name: Create automatic PR from SB issue

on:
  workflow_dispatch: # Manual trigger
  issues:
    types: [opened]

jobs:
  create_pr_from_sb_issue:
    runs-on: [self-hosted, windows]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create a new PR from SB Issue
        id: create_pr_from_sb_issue
        uses: actions/github-script@v7
        with:
          script: |
            const createPRFromSBIssue = require('./.github/workflows/create_PR_from_SB_issue.js');
            const prNumber = await createPRFromSBIssue({ github, context, exec });
            core.setOutput('prNumber', prNumber);

      - name: Manual Trigger SB_and_BB_PR_checker
        id: pr_checker
        uses: actions/github-script@v7
        with:
          script: |
            const { _SBAndBBPRChecker } = require('./.github/workflows/SB_and_BB_PR_checker.js');
            await _SBAndBBPRChecker({ github, prNumber: ${{ steps.create_pr_from_sb_issue.outputs.prNumber }} });


