name: Create Compiler Label

on:
  workflow_dispatch: # Manual trigger
  workflow_call:

jobs:
  jai_version_workflow:
    uses: ./.github/workflows/jai_version.yml

  create_compiler_label:
    runs-on: [self-hosted, windows]
    needs: jai_version_workflow
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Create Compiler Label if it does not exist
      uses: actions/github-script@v7
      with:
        script: |
          console.log("${{ needs.jai_version_workflow.outputs.version }}");
          console.log("${{ needs.jai_version_workflow.outputs.jai_version.version }}");

          /*
          const labelName = "${{ steps.jai_version.outputs.version }}";

          console.log(new Date().toISOString());
          
          // Check if the label exists
          const { data: labels } = await github.rest.issues.listLabelsForRepo({
            owner: context.repo.owner,
            repo: context.repo.repo,
          });

          const labelExists = labels.some(label => label.name === labelName);

          // If the label doesn't exist, create it
          if (!labelExists) {
            await github.rest.issues.createLabel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: labelName,
            });
          }
          */
