# [ ] cross platform support

# [~] Create Label on Issue, PR, and (??test suit??) if not exist
# [x] Add label on Issue/PR create
# [x] Jai Version Task
# [x] refactor to share js files
# [ ] Update issue status on !Emailed
# [ ] issue name (clasification only) from PR name or classification dropdown?
# [ ] mention issue from PR
# [ ] create message that further discussion are supposed to be held on issue
# [ ] parse description
# [ ] parse !jonsaid
# [ ] parse and add not emailed tag
# [ ] jai dropdown and parsing of older version
# [ ] parse code snipped if single file
# [ ] PR and issue template (issue: i will make pr checkbox)

# [x] Auto run Testsuit on push
# [ ] (Auto run testsuit on approval of PR)
# [ ] create test result json
# [ ] run for past 3-5 jai versions
# [ ] Update issue on test results
#     [ ] change state, dates, labels
#     [ ] how to map name to issue number? maybe we DO need an id
# [ ] Update readme on test results
#     [ ] link issue number
#     [ ] foldable source code if single file, otherwise link
#     [ ] add 'new' section, if reported at compilerversion (could still bebroken backwards) 
#         or reopen compiler version (!= last encounter, maybe change that?)
#     [ ] column ordering?
#     [ ] recently fixed section (last 2 compiler versions?)

name: Create Issue on PR Merge

on:
  workflow_dispatch: # Manual trigger
  # push:
  #   branches:
  #     - master
  pull_request:
    types: [closed]

jobs:  
  create_issue:
    runs-on: [self-hosted, windows]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Generate unique prefix for the new issue
      uses: actions/github-script@v7
      id: generate_prefix
      if: github.event_name == 'pull_request'
      with:
        script: |
          const issues = await github.paginate(github.rest.issues.listForRepo, {
            owner: context.repo.owner,
            repo: context.repo.repo,
            creator: 'github-actions'
          });

          console.log(issues);

          const datePrefix = new Date().toISOString().split('T')[0];
          let maxId = 0;
          
          issues.forEach(issue => {
            const match = issue.title.match(/(\d{4}-\d{2}-\d{2})-(\d{5})/);
            console.log(issue);
            if (match) {
              const id = parseInt(match[2], 10);
              if (id > maxId) {
                maxId = id;
              }
            }
          });

          const prefix = `${datePrefix}-${String(maxId + 1).padStart(5, '0')}`;
          console.log(prefix);
          core.setOutput('prefix', prefix);


    - name: Create a new issue
      uses: actions/github-script@v7
      if: github.event_name == 'pull_request'
      with:
        script: |
          const get_jai_version = require('./.github/workflows/jai_version.js');
          
          const currentJaiVersion = await get_jai_version();
          const prefix = "${{ steps.generate_prefix.outputs.prefix }}";
          const date = new Date().toISOString().split('T')[0];
          const prNumber = context.payload.pull_request.number;
          const prTitle = context.payload.pull_request.title;
          const prBody = context.payload.pull_request.body;

          const issueTitle = `${prefix}-${prTitle}`;
          const issueBody = `
          **Status:**
          
          | Test Name | Status | Emailed In | First Encounter | First Encounter Version | Last Encountered | Last Encountered Version | Fix Date | Fix Date Version |
          | :---: | :---: | :---: | :---: | :---: | :---: | :---: | :---: | :---: |
          | EC1_polymorph_1.jai | Open | ❌ | ${date} | ${currentJaiVersion} | ${date} | ${currentJaiVersion} |  |  |
          `;

          const { data: issue } = await github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: issueTitle,
            body: issueBody
          });

          console.log(issue);

          // Label will be added by other workflow


          
