name: Create Issue on PR Merge

on:
  workflow_dispatch: # Manual trigger
  workflow_call:

jobs:
  create_issue:
    runs-on: [self-hosted, windows]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Create new Compiler Version Label if it does not exist
      uses: actions/github-script@v7
      with:
        script: |
          const labelName = "${{ steps.jai_version.outputs.version }}";

          console.log(new Date().toISOString());
          
          // Check if the label exists
          const { data: labels } = await github.rest.issues.listLabelsForRepo({
            owner: context.repo.owner,
            repo: context.repo.repo,
          });

          const labelExists = labels.some(label => label.name === labelName);

          // If the label doesn't exist, create it
          if (!labelExists) {
            await github.rest.issues.createLabel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: labelName,
            });
          }
