name: Create automatic PR from issue

on:
  issues:
    types: [opened, edited]

jobs:
  create_pr:
    runs-on: [self-hosted, windows]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create a new issue
        uses: actions/github-script@v7
        with:
          script: |
            const { data: issue } = await github.rest.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number
            });
            console.log(issue);

            const regex = /\[SB\]: (.{5,})/gm;
            const title_text = [...issue.title.matchAll(regex)][0][1] || "";