name: Create automatic PR from SB issue

on:
  workflow_dispatch: # Manual trigger
  issues:
    types: [opened, edited] # @todo remove edited

jobs:
  create_pr_from_sb_issue:
    runs-on: [self-hosted, windows]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create a new PR from SB Issue
        id: create_pr_from_sb_issue
        uses: actions/github-script@v7
        with:
          script: |
            const createPRFromSBIssue = require('./.github/workflows/create_PR_from_SB_issue.js');
            const prNumber = await createPRFromSBIssue({ github, context, exec });
            core.setOutput('prNumber', prNumber);

      # Ideally, we would like to trigger the SB_and_BB_PR_checker workflow here automatically, but
      # since this is disabled when using the GITHUB_TOKEN, we will trigger it manually.
      # https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/triggering-a-workflow#triggering-a-workflow-from-a-workflow

      - name: Manual Trigger SB_and_BB_PR_checker
        id: pr_checker
        uses: actions/github-script@v7
        with:
          script: |
            const { _SBAndBBPRChecker } = require('./.github/workflows/SB_and_BB_PR_checker.js');
            await _SBAndBBPRChecker({ github, contextRepo: context.repo, prNumber: ${{ steps.create_pr_from_sb_issue.outputs.prNumber }} });


