name: Create automatic PR from SB issue

on:
  workflow_dispatch: # Manual trigger
  issues:
    types: [opened, edited] #@todo remove edited

jobs:
  create_pr_from_sb_issue:
    runs-on: [self-hosted, windows]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create a new PR from SB Issue
        uses: actions/github-script@v7
        with:
          script: |
            const createPRFromSBIssue = require('./.github/workflows/create_PR_from_SB_issue.js');
            await createPRFromSBIssue({github, context, exec});


