name: Create automatic PR from issue

on:
  issues:
    types: [opened, edited]

jobs:
  create_pr:
    runs-on: [self-hosted, windows]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create a new issue
        uses: actions/github-script@v7
        with:
          script: |
            const { data: issue } = await github.rest.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number
            });
            // console.log(issue);

            const regex = /(?:\[SB\]): (.{10,})/gmi;
            const match = [...issue.title.matchAll(regex)][0] || [];
            const title_text = match[1]; // maybe undefined
            console.log(1, title_text);
            console.log(2, match);
            if (title_text === undefined) return;
            console.log(3, title_text);
