name: Create Issue on PR Merge

on:
  workflow_dispatch: # Manual trigger
  push:
    branches:
      - master
  pull_request:
    types: [closed]

jobs:
  create_issue:
    runs-on: [self-hosted, windows]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create a new issue
      uses: actions/github-script@v7
      with:
        script: |
          const issueTitle = 'New Issue Created via GitHub Actions';
          const issueBody = 'This is an issue automatically created by GitHub Actions.';

          await github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: issueTitle,
            body: issueBody
          });
