name: Get Jai Version

on:
  workflow_dispatch: # Manual trigger
  workflow_call:
   outputs:
      version:
        value: ${{ jobs.get_jai_version.steps.jai_version.version }}

jobs:
  get_jai_version:
    runs-on: [self-hosted, windows]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
  
    # JS Version doesnt seem to work due a jai bug not showing the output in subprocesses or smth
    - name: Run Jai -version and capture output
      id: jai_version_output
      run: |
        $output = jai -version
        echo $output
        echo "version=$output" >> $GITHUB_OUTPUT
        
          
    - name: Run jai -version and parse output
      uses: actions/github-script@v7
      id: jai_version
      with:
        script: |
          let jaiVersionOutput = 'Version: beta 0.1.092, built on 4 August 2024.';
          
          /*
          const options = {};
          options.silent = false;
          options.ignoreReturnCode = true;
          options.listeners = {
            stdout: (data) => {
              jaiVersionOutput += data.toString();
            },
            stderr: (data) => {
              jaiVersionOutput += data.toString();
            },
            stdline: (string) => {
              jaiVersionOutput += string;
            },
            errline: (string) => {
              jaiVersionOutput += string;
            }
          };

          // Replace 'your-executable' with the command you want to run
          await exec.exec('jai', [], options);
          */
          
          console.log(jaiVersionOutput);

          const versionMatch = jaiVersionOutput.match(/beta \d+\.\d+\.\d+/);
          const version = versionMatch ? versionMatch[0].replace(/\s+/g, '-') : 'VersionNotFound';

          console.log(`Parsed Version: ${version}`);
          core.setOutput('version', version);
