name: Get Jai Version

on:
  workflow_dispatch: # Manual trigger
  workflow_call:
   outputs:
      version:
        value: ${{ jobs.get_jai_version.outputs.version }}

jobs:
  get_jai_version:
    runs-on: [self-hosted, windows]
    outputs:
      version: ${{ steps.jai_version.outputs.version }}
    
    steps:     
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Run jai -version and parse output
      uses: actions/github-script@v7
      id: jai_version
      with:
        script: |
          const get_jai_version = require('./.github/workflows/jai_version.js');
          const jai_version = await get_jai_version();

          console.log(`Parsed Version: ${jai_version}`);
          core.setOutput('version', jai_version);
