name: Run Test Suit

on:
  workflow_dispatch: # Manual trigger
  push:
    branches:
      - master

jobs:
  linux_testo:
    runs-on: [self-hosted, linux]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Bug Suit
        uses: actions/github-script@v7
        with:
          script: |
            console.log('Running Bug Suit');

  run_test_suit:
    runs-on: [self-hosted, windows]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Bug Suit
        uses: actions/github-script@v7
        with:
          script: |
            const runTestSuitAndUpdate = require('./.github/workflows/run_test_suit_and_update.js');
            await runTestSuitAndUpdate({ github, context, exec, io });