name: Run Test Suit

on:
  workflow_dispatch: # Manual trigger
  push:
    branches:
      - master

jobs:
  run_test_suit:
    strategy:
      matrix:
        platform: [windows, linux]

    outputs:
      test_suit_output_windows: ${{ steps.run-bug-suit.outputs.windows }}
      test_suit_output_linux: ${{ steps.run-bug-suit.outputs.linux }}

    runs-on: 
     - self-hosted
     - ${{ matrix.platform }}
     
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Bug Suit
        id: run-bug-suit
        uses: actions/github-script@v7
        with:
          script: |
            const { runTestSuitAndUpdate } = require('./.github/workflows/run_test_suit_and_update.js');
            const testSuitOutput = await runTestSuitAndUpdate({ github, context, exec, io });
            core.setOutput('${{ matrix.platform }}', testSuitOutput);

      # @todo check if we can overwrite it or else delete it below!
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: test_results_${{ matrix.platform }}
          path: test_results.json
          retention-days: 1 # we only need this for the next job

  update_github_files_and_issues:
    needs: run_test_suit
    runs-on: [self-hosted]
    steps:
      - name: Download Windows test results
        uses: actions/download-artifact@v4
        with:
          name: test_results_windows
          path: windows

      - name: Download Linux test results
        uses: actions/download-artifact@v4
        with:
          name: test_results_linux
          path: linux

      - name: Update Github Files and Issues
        uses: actions/github-script@v7
        with:
          script: |
            console.log('Windows:', ${{ needs.run_test_suit.outputs.test_suit_output_windows }});
            const testsuit = {
              windows: JSON.parse(${{ needs.run_test_suit.outputs.test_suit_output_windows }}),
              linux: JSON.parse(${{ needs.run_test_suit.outputs.test_suit_output_linux }}),
            };
            console.log(testsuit);
            const { updateGithubIssuesAndFiles } = require('./.github/workflows/run_test_suit_and_update.js');
            await updateGithubIssuesAndFiles({ github, context, exec, io });

      # @todo
      # - name: Download artifact to specific directory
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: test_results_macos
      #     path: macos