name: Run Test Suit

on:
  workflow_dispatch: # Manual trigger
  push:
    branches:
      - master

jobs:
  run_test_suit:
    runs-on: [self-hosted, windows]

    steps:
      - name: hashes
        run: |
          CertUtil -hashfile .github/workflows/run_test_suit_and_update.js SHA256
          CertUtil -hashfile .github/workflows/run_test_suit_and_update.yml SHA256

      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          persist-credentials: false

      - name: Run Bug Suit
        uses: actions/github-script@v7
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          script: |
            const runTestSuitAndUpdate = require('./.github/workflows/run_test_suit_and_update.js');
            await runTestSuitAndUpdate({ github, context, exec, io });

      - name: hashes
        run: |
          CertUtil -hashfile .github/workflows/run_test_suit_and_update.js SHA256
          CertUtil -hashfile .github/workflows/run_test_suit_and_update.yml SHA256