name: Run Test Suit

on:
  workflow_dispatch: # Manual trigger
  push:
    branches:
      - master

jobs:
  run_test_suit:
    strategy:
      matrix:
        platform: [windows, linux]
    runs-on: 
     - self-hosted 
     - ${{ matrix.platform }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Bug Suit
        uses: actions/github-script@v7
        with:
          script: |
            const runTestSuitAndUpdate = require('./.github/workflows/run_test_suit_and_update.js');
            await runTestSuitAndUpdate({ github, context, exec, io });