name: PR Checker

on:
  workflow_dispatch: # Manual trigger
  pull_request:
    types: [opened, edited]

jobs:
  sb_bb_pr_checker:
    runs-on: [self-hosted, windows]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: PR Checker
        uses: actions/github-script@v7
        with:
          script: |
            const { SBAndBBPRChecker } = require('./.github/workflows/SB_and_BB_PR_checker.js');
            await SBAndBBPRChecker({ github, context });
