name: Run Test Suit

on:
  workflow_dispatch: # Manual trigger
  pull_request:
    types: [opened, edited]

jobs:
  run_test_suit:
    runs-on: [self-hosted, windows]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Bug Suit
        uses: actions/github-script@v7
        with:
          script: |
            const { SBAndBBPRChecker } = require('./.github/workflows/SB_and_BB_PR_checker.js');
            await SBAndBBPRChecker({github, context, exec, io});
