name: Custom Command Workflows

on:
  push:
    branches:
      - master
  workflow_dispatch: # Manual trigger

jobs:
  run-on-windows:
    runs-on: [self-hosted, windows]

    steps:
      # - shell: cmd
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run custom command on Windows
        run: |
          jai .\bug_suit.jai
