name: PR Checker

on:
  workflow_dispatch: # Manual trigger
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  sb_bb_pr_checker:
    runs-on: [self-hosted, windows]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: PR Checker
        uses: actions/github-script@v7
        with:
          script: |
            const { SBAndBBPRChecker } = require('./.github/workflows/validate_PR_and_merge_automation.js');
            await SBAndBBPRChecker({ github, context });

  validate_and_merge_pr:
    runs-on: [self-hosted, windows]
    needs: sb_bb_pr_checker
    environment: test

    steps:
      - name: Checkout PR Branch
        uses: actions/checkout@v4
        with:
          # Checkout the pull request branch instead of master
          ref: ${{ github.event.pull_request.head.ref }}
          # Fetch all history to ensure you get the full PR context
          # fetch-depth: 0

      - name: Validate new Test and Merge Pull Request
        uses: actions/github-script@v7
        with:
          script: |
            const { validateAddedTestAndMergeOnSuccess } = require('./.github/workflows/validate_PR_and_merge_automation.js');
            await validateAddedTestAndMergeOnSuccess({ github, exec, contextRepo: context.repo, prNumber: context.issue.number });

            
