name: PR Checker

on:
  workflow_dispatch: # Manual trigger
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  validate_pr_structure:
    runs-on: [self-hosted, windows]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: PR Checker
        uses: actions/github-script@v7
        with:
          script: |
            const { validatePRStructure } = require('./.github/workflows/validate_PR_and_merge_automation.js');
            await validatePRStructure({ github, context });

  validate_added_test_and_merge_pr:
    runs-on: [self-hosted, windows]
    needs: validate_pr_structure
    # environment: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Validate new Test and Merge Pull Request
        uses: actions/github-script@v7
        with:
          script: |
            const { validateAddedTestAndMergeOnSuccess } = require('./.github/workflows/validate_PR_and_merge_automation.js');
            await validateAddedTestAndMergeOnSuccess({ github, exec, io, contextRepo: context.repo, prNumber: context.issue.number, prRef: '${{ github.event.pull_request.head.ref }}' });

            
