name: PR Checker

on:
  workflow_dispatch: # Manual trigger
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  validate_pr_structure:
    runs-on: [self-hosted, windows]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: PR Checker
        uses: actions/github-script@v7
        with:
          script: |
            const { validatePRStructure } = require('./.github/workflows/validate_PR_and_merge_automation.js');
            await validatePRStructure({ github, context });

  validate_added_test_and_merge_pr:
    runs-on: [self-hosted, windows]
    needs: validate_pr_structure
    # environment: test # @todo do we only wanna run this on forks?

    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          persist-credentials: false
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Validate new Test and Merge Pull Request
        uses: actions/github-script@v7
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          script: |
            const { validateAddedTestAndMergeOnSuccess } = require('./.github/workflows/validate_PR_and_merge_automation.js');
            await validateAddedTestAndMergeOnSuccess({ github, exec, io, contextRepo: context.repo, prNumber: context.issue.number });

      # Not sure why the merge below only works after Checking out the PR again.
      # If we dont do this, the merge will fail with 'Head branch is out of date'
      # - name: Checkout Updated PR
      #   uses: actions/checkout@v4
      #   with:
      #     token: ${{ steps.app-token.outputs.token }}
      #     persist-credentials: false
      #     ref: ${{ github.event.pull_request.head.ref }}

      # - name: Merge PR
      #   uses: actions/github-script@v7
      #   with:
      #     github-token: ${{ steps.app-token.outputs.token }}
      #     script: |
      #       const mergeResponse = await github.rest.pulls.merge({
      #         ...context.repo,
      #         pull_number: context.issue.number,
      #         merge_method: 'squash'  // Use 'merge', 'squash', or 'rebase' depending on your needs
      #       });

            
